apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-monitoring-thanos-gateway
  namespace: cattle-monitoring-system
spec:
  tls:
  - hosts:
    - {{ index .Values "global" "fleet" "clusterLabels" "management.cattle.io/cluster-name" }}.demo.skrzypek.us
    secretName: wildcard
  rules:
  - host: {{ index .Values "global" "fleet" "clusterLabels" "management.cattle.io/cluster-name" }}.demo.skrzypek.us
    http:
      paths:
      - backend:
          service:
            name: rancher-monitoring-prometheus
            port:
              number: 10901
        path: /
        pathType: ImplementationSpecific
